[snowflake]
user = "your_snowflake_user"
password = "your_snowflake_password"
account = "your_snowflake_account"
warehouse = "your_snowflake_warehouse"
database = "your_snowflake_database"
schema = "your_snowflake_schema"
